Import the numpy module

In [34]:
import numpy as np

Create a 1d numpy array called arr1 that looks like the one below. Display it.

In [35]:
arr1 = np.array([3,6,9,12,15])
arr1

array([ 3,  6,  9, 12, 15])

Print out the 3rd element of the array.

In [36]:
arr1[2]

9

Create a 2d numpy array called arr2 that looks like the one below. Display it.

In [37]:
list2 = [[2, 4, 6], [3, 6, 9], [4, 8, 12]]
arr2 = np.array(list2)
arr2

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

Print out the element at row=3,col=2.

In [39]:
arr2[2][1]

8

Create an array that goes from 0 to 100 with step=3. Display it.

In [41]:
#np.arange(start,stop,step)
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Create a 10x5 2d array filled with zeroes. Display it.

In [42]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create an array called lin1d, that has 100 data points spaced between 57 and 108. Display it.

In [43]:
#np.linspace(start,stop,number)
lin1d = np.linspace(57,108,100)
lin1d

array([ 57.        ,  57.51515152,  58.03030303,  58.54545455,
        59.06060606,  59.57575758,  60.09090909,  60.60606061,
        61.12121212,  61.63636364,  62.15151515,  62.66666667,
        63.18181818,  63.6969697 ,  64.21212121,  64.72727273,
        65.24242424,  65.75757576,  66.27272727,  66.78787879,
        67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
        69.36363636,  69.87878788,  70.39393939,  70.90909091,
        71.42424242,  71.93939394,  72.45454545,  72.96969697,
        73.48484848,  74.        ,  74.51515152,  75.03030303,
        75.54545455,  76.06060606,  76.57575758,  77.09090909,
        77.60606061,  78.12121212,  78.63636364,  79.15151515,
        79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
        81.72727273,  82.24242424,  82.75757576,  83.27272727,
        83.78787879,  84.3030303 ,  84.81818182,  85.33333333,
        85.84848485,  86.36363636,  86.87878788,  87.39393939,
        87.90909091,  88.42424242,  88.93939394,  89.45

Reshape lin1d to be 10x10 and call it lin2d. Display it.

In [44]:
lin2d = lin1d.reshape(10,10)
lin2d

array([[ 57.        ,  57.51515152,  58.03030303,  58.54545455,
         59.06060606,  59.57575758,  60.09090909,  60.60606061,
         61.12121212,  61.63636364],
       [ 62.15151515,  62.66666667,  63.18181818,  63.6969697 ,
         64.21212121,  64.72727273,  65.24242424,  65.75757576,
         66.27272727,  66.78787879],
       [ 67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
         69.36363636,  69.87878788,  70.39393939,  70.90909091,
         71.42424242,  71.93939394],
       [ 72.45454545,  72.96969697,  73.48484848,  74.        ,
         74.51515152,  75.03030303,  75.54545455,  76.06060606,
         76.57575758,  77.09090909],
       [ 77.60606061,  78.12121212,  78.63636364,  79.15151515,
         79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
         81.72727273,  82.24242424],
       [ 82.75757576,  83.27272727,  83.78787879,  84.3030303 ,
         84.81818182,  85.33333333,  85.84848485,  86.36363636,
         86.87878788,  87.39393939],
       [ 8

Print out the shape of lin1d and lin2d.

In [45]:
print("lin1d:" , lin1d.shape)
print("lin2d:" , lin2d.shape)

lin1d: (100,)
lin2d: (10, 10)


Generate a 5x5 array of random numbers called nums. Display it.

In [46]:
nums = np.random.rand(5,5)
nums

array([[0.81056432, 0.68983473, 0.22655862, 0.62753092, 0.68427522],
       [0.01268509, 0.95754675, 0.08406081, 0.829706  , 0.51349312],
       [0.61877793, 0.98791231, 0.74778745, 0.05939242, 0.46479009],
       [0.50977731, 0.58300095, 0.90487206, 0.19476549, 0.13330434],
       [0.50984071, 0.36848734, 0.56386283, 0.38590696, 0.65560161]])

Print out the min, max and mean of the nums array.

In [47]:
print("Min:", nums.min())
print("Max:", nums.max())
print("Mean:", nums.mean())

Min: 0.012685086584237615
Max: 0.9879123125315211
Mean: 0.5249734154652574


Multiple the entire array nums x2 and store it back in nums. Display the result.

In [49]:
nums = nums * 2
nums

array([[3.24225729, 2.75933891, 0.90623447, 2.5101237 , 2.73710088],
       [0.05074035, 3.830187  , 0.33624325, 3.31882401, 2.05397247],
       [2.47511171, 3.95164925, 2.99114981, 0.23756968, 1.85916035],
       [2.03910925, 2.33200381, 3.61948825, 0.77906195, 0.53321737],
       [2.03936286, 1.47394935, 2.25545133, 1.54362783, 2.62240646]])

Select rows 1 to 2 and cols 2 to 3 and display the result.

In [50]:
nums[1:3,2:4]

array([[0.33624325, 3.31882401],
       [2.99114981, 0.23756968]])

Modify that same selection by multiplying it x10, then display the new nums array.

In [51]:
nums[1:3,2:4] = nums[1:3,2:4] * 10
nums

array([[ 3.24225729,  2.75933891,  0.90623447,  2.5101237 ,  2.73710088],
       [ 0.05074035,  3.830187  ,  3.3624325 , 33.18824007,  2.05397247],
       [ 2.47511171,  3.95164925, 29.91149807,  2.37569677,  1.85916035],
       [ 2.03910925,  2.33200381,  3.61948825,  0.77906195,  0.53321737],
       [ 2.03936286,  1.47394935,  2.25545133,  1.54362783,  2.62240646]])